name: loreal_isp_supervisor_flutter
description: Flutter application for Loreal ISP Supervisor

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  http: "^0.11.3+16"
  shared_preferences: "0.4.2"
  flutter_webview_plugin: "^0.1.5"
  sqflite: "^0.11.0"
  device_info: "^0.2.1"
  camera: ^0.2.1
  video_player: "0.5.2"
  path_provider: 0.3.0
  simple_permissions: ^0.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
        - assets/loreal1.png
        - assets/download_grey.png
        - assets/entry_grey.png
        - assets/exit_grey.png
        - assets/export.png
        - assets/geotag_grey.png
        - assets/upload_grey.png
        - assets/baseline_how_to_reg_black_48.png
        - assets/visitor_login.png
        - assets/absent.png
        - assets/promoter_performance.png
        - assets/attendance.png
        - assets/anim.gif
        - assets/loreal_aish.gif
        - assets/background.jpg
        - assets/background2.jpg
        - assets/background3.jpg
        - assets/nav_bg.png
        - assets/exit.png
        - assets/reports.png
        - assets/mark_attendance.png
        - assets/download.png
        - assets/daily_entry.png
        - assets/camera_icon.png
        - assets/tick_icon.png

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
